### ISSUE TITLE
make run does a segmentation fault

### ISSUE THREAD

**Issue by alt-romes** [alt-romes/programmer-calculator#11]
Hi everyone,

When running `make run`, the whole program crashes with the error `Segmentation fault`

I think you're the only one who can handle this right now, @DevManu-de (since we haven't studied the makefile yet)

--- EDIT ---
Actually, running `output/pcalc` also crashes with segmentation fault.
Only `./pcalc` created in the root directory is run successfully

Thank you,
~romes

**Comment by DevManu-de** [comment]
Hello,

I fixed it. It now runs fine as before.
Please remove the `pcalc` from your root directory because all executables will end up in the output folder.

I should have tested the execution before making a pull request. Im sorry for the mistake.

DevManu-de

**Comment by alt-romes** [comment]
Hi,

Could you make it so that the `pcalc` final executable is put in the root folder?
This way I won't have to test the brew formula again, and I think I rather have it that way.
Is there any particular reason why you think the executable should be in an output folder?

Thank you,
romes
