### ISSUE TITLE
Adding duplicate entries to the search history

### ISSUE THREAD

**Issue by alt-romes** [alt-romes/programmer-calculator#12]
Hi,

We should assert that when an entry is added to the search history, it isn't at the top of the stack yet.

Right now, if inputted into the calculator `10`, followed by `10`, you'll can scroll twice up in history, and it would be best if you couldn't have duplicates back to back.

Also, there's no size check when adding to history, it might possibly blow up, someday we might need to fix that (even though the `size 100` is "good enough" right now - it was our "lazy choice")

Thank you,
~romes

**Comment by DevManu-de** [comment]
Hi,

I will try to take care of this.

DevManu-de
