### ISSUE TITLE
Multiple operations per input

### ISSUE THREAD

**Issue by DevManu-de** [alt-romes/programmer-calculator#13]
Hello everyone,

Currently pcalc only takes one operator per input line. But if you enter multiple you end up with a wrong result and a messed up `History :` display.

I think this is becomming more important because we have implemted the history scrolling.

DevManu-de

**Comment by alt-romes** [comment]
Hi,

It would be helpful if you could you give a concrete example of this :)

Ty,
~romes

**Comment by DevManu-de** [comment]
Hey,

The first image shows the input and the second one shows the messed up `History :`

![20210128 181804](https://user-images.githubusercontent.com/68355512/106174140-fba6d180-6194-11eb-9117-9a948c8afbb6.jpg)
![20210128 181809](https://user-images.githubusercontent.com/68355512/106174164-02354900-6195-11eb-85bf-df6cfd03a61e.jpg)

DevManu-de

**Comment by DevManu-de** [comment]
Hey,

Is someome looking at this issue at the moment?
I would do it but for now I dont have an idea on how to implement it.

DevManu-de

**Comment by thurstylark** [comment]
What about using something like [readline](https://tiswww.case.edu/php/chet/readline/rltop.html)?

**Comment by alt-romes** [comment]
No one is trying to implement this at the moment. I have a vague idea on how to do it, but I'm open to suggestions.
Right now I'm thinking about sitting the idea in the background and come to back to it in a few days

**Comment by DevManu-de** [comment]
Hello @thurstylark, 

do you have an idea on how to implement it if so please share your thoughts,
Please note that getting the input is already implemented its about the algorithm after that.
I am looking for a solution that doesnt require us to reimplement the `process_input()` completely.

**Comment by alt-romes** [comment]
@DevManu-de we won't have to reimplement it completely.

We only have to edit and add to the first if, from line 167 to 252 from `main`

If you really want me to I can get started on it.

ty, ~romes

**Comment by thurstylark** [comment]
So, just to be up-front, I've done *very* little C, and haven't actually used readline in a project before, so I'm deferring to docs and examples for the most part. I'm definitely open to being corrected if I'm totally off-base

https://tiswww.case.edu/php/chet/readline/readline.html#SEC23

https://eli.thegreenplace.net/2016/basics-of-using-the-readline-library/

From what I understand, readline would replace all or most of `get_input()`, and then readline's history calls can be used to bring in the history scrollback familiar to those who use the likes of bash.

Whether this is appropriate to replace the existing history setup, I'm not sure, but thought it might be worth considering.

**Comment by DevManu-de** [comment]
Hello, @thurstylark 

the GNU readline library seems to make things a little complicated according to https://stackoverflow.com/questions/691652/using-gnu-readline-how-can-i-add-ncurses-in-the-same-program and the ncuses FAQ https://invisible-island.net/ncurses/ncurses.faq.html#readline_library

I have played around with ncurses and readline a bit and it causes the problems mentioned in ncurses FAQ.

Therefore I suggest keeping the current `get_input()` but if you can supply some code with readline that works with pcalc we can take a much closer look at it.

DevManu-de
