### ISSUE TITLE
Segmentation fault on 1+ followed by +1

### ISSUE THREAD

**Issue by alt-romes** [alt-romes/programmer-calculator#21]
Something goes wrong with the history memory reallocation when adding 1+ <enter>followed by +1 <enter>

@DevManu-de since you did the history realloc do you think you could check this out? You'll probably be faster than me

Thank you,
~romes

PS: I'm currently working on the inline-math.

**Comment by alt-romes** [comment]
I just realised this was actually my fault

I remembered now to test the actual program instead of the version I was working on, and it's actually all working alright.

I'm sorry, and thank you again :)

**Comment by DevManu-de** [comment]
No problem :)
