### ISSUE TITLE
get_input can't handle %

### ISSUE THREAD

**Issue by alt-romes** [alt-romes/programmer-calculator#25]
Hello,

Inserting the operator `%` currently doesn't work - you need to press it twice.
This is due to the fact that printf will only display `%` when escaped by itself: `%%`

ty
~romes

**Comment by DevManu-de** [comment]
Hi,
maybe its the bets to switch to another input function.
My get_input doesnt handle this well and possibly other chars too.
Ill take a look at GNU readline as @thurstylark mentioned.

DevManu-de

**Comment by alt-romes** [comment]
Hi,
The `readline` sounds nice, but if it overcomplicates I think it would be better to maintain the simple history scrolling we implemented and the simple `get_input` function, and fix these edge cases.

Thank you.

PS: I'm almost almost done with the inline math with more than 2 operands
