### ISSUE TITLE
Data loss when resizeing

### ISSUE THREAD

**Issue by DevManu-de** [alt-romes/programmer-calculator#3]
Hello,
after playing a little bit with pcalc I have found out, that the calculation previously entered gets lost when I resize my terminal.
By lost I mean Decimal, Hex, Binary and History is set to 0.

Possibly important information about my system:
-  Running Arch Linux
- Terminal is st and alacritty (both have the issue)
- Window manager is dwm

If required or wanted I can supply more information or even code.

Thanks in advance.
DevManu-de

**Comment by alt-romes** [comment]
thank you, we'll try to fix it :) 👍

**Comment by alt-romes** [comment]
it's fixed: run `brew update`, and then `brew upgrade pcalc` :)
