### ISSUE TITLE
% causes bugs and crashes

### ISSUE THREAD

**Issue by DevManu-de** [alt-romes/programmer-calculator#31]
Hello,

I have been testing with the % sign and found out that entering % requires to press backspace twice.
In addition to that I found out that entering `%` and pressing `backspace` one and then enter `G` causes pcalc to output `4.64142e-310` other combinations of `%` `backspace` and `other keys` cause output like `(NULL)` or even freeze pcalc.

I have listed some combination that I have found out.
- % + backsapce + G = `4.64142e-310`
- % + backspace + S = `(NULL)`
- % + backspace + C = pcalc freezes (CTRL-C exits, Enter crashes)
- % + backspace + D = `0`

As if this is not enough I found out that entering `%d` or any other `printf` like format pcalc crashes immediately with the response `Floating point exception (core dumped)`

DevManu-de

**Comment by alt-romes** [comment]
The first problems are fixed, now we just need to take care of the last one

**Comment by alt-romes** [comment]
Hey!

It's fixed.

At the time I decided that displaying an error message when a division by zero happened required too much effort, so I just returned division by zero as 0 - however maybe we want to change that now.

Thank you,
~romes
