### ISSUE TITLE
Right arrow and Left arrow should navigate input

### ISSUE THREAD

**Issue by alt-romes** [alt-romes/programmer-calculator#33]
Hello,

When using the history feature, I feel the need to edit what I wrote more than to add things.

Right now, when the left and right arrow key are pressed, a D or C is inserted into the input line, instead of moving the cursor left or right, to edit the input.

Thank you,
~romes

**Comment by alt-romes** [comment]
After merging #42 we are now working on using the ncurses cursor instead of the `_`

@kippenjongen I've just committed 2 lines to make the cursor follow the underscore

Are you going to work on it now, do you want to do it, or should I try to implement it?

**Comment by kippenjongen** [comment]
I'll happily have a go at it

**Comment by alt-romes** [comment]
Before merging the `side-arrows` branch into `master` (and possibly releasing a new version) we should try playing a bit more with it and see if it breaks.

Let me know if you find any bugs :)

Ty,
~romes
