### ISSUE TITLE
«Compiling the code into an executable file»

### ISSUE THREAD

**Issue by Rapta-08** [alt-romes/programmer-calculator#37]
I am sorry, but I haven't understand for the Debian distro, what do you mean with «compile the code into an executable file» and the command make. Whitch command sould I use?? I'd like to have this culculator at my PC, so if you could explain it to me it would be such a huge help!!

**Comment by alt-romes** [comment]
Okay!
Basically, there are a couple of ways to install the program.
Two of them are with a package installer (`brew` or `yay` or somehow from an AUR package)

The other way is to download the repository, and build the program yourself

If you want to build from source, first you need to install the `ncurses` dependency
```
sudo apt-get install libncurses5-dev libncursesw5-dev
```

Then you need to clone the repository, to get the code in your computer
```
git clone https://github.com/alt-romes/programmer-calculator
```

Then you need to move to the repository you cloned
```
cd programmer-calculator
```

Then you need to compile the code into an executable, by running:
```
make
```
which will read the compile instructions in the `makefile` to compile the code

Then you'll have an executable called `pcalc`, but you want to move it to a directory reachable by $PATH - that way you can run `pcalc` from anywhere in the computer. I think `/usr/local/bin` is a location accessible by $PATH in most unix based computers. So you move the executable to that location
```
mv -i pcalc /usr/local/bin
```

Now you should be able to run `pcalc`.

You don't even need the program folder anymore, so you could do, to delete the downloaded code:
```
cd .. ; rm -rf programmer-calculator
```

I'll try to make the instructions a little bit more clear . Thanks for pointing this out

**Comment by Rapta-08** [comment]
I did it!! Thank you!!

**Comment by alt-romes** [comment]
You're welcome, thank you too :)
