### ISSUE TITLE
Up arrow scrolls history (like a terminal) idea

### ISSUE THREAD

**Issue by DevManu-de** [alt-romes/programmer-calculator#4]
Hello,
I saw that the TODO says `Up arrow scrolls history (like a terminal)` and so I decided to implement the input algorithim that takes the arrow keys directly (without enter) and handles the other keys like normal.

Before I make a pull request I want you to take a look at the current code (https://github.com/DevManu-de/programmer-calculator/tree/extended_input) and maybe give me some feedback.

Important:
- My code was only tested on arch linux.
- Only the input algorithim is implemented but not the history scroll. (I would prefer that this is implemented before I make a pull request to master)
- All changes were made in `main.c` in lines 175 to 221.

Maybe you can make a new branch in your repository for a pull request.

If you need more detail on the code just tell me.

Im looking forward to your answer
DevManu-de

**Comment by alt-romes** [comment]
Hallo DevManu,

I checked out your fork, it looks great!

Before issuing the pull request, I just want to suggest switching your line 212 and 214 to: `mvwprintw(inputwin, 1, 22 + i--," ")`, since there's no need to call strlen() if `i` holds the size, as long as you only decrement it after printing (the `i--` part)

I really appreciate it,
Dankeschön!

PS: I'm not sure when I'll look at implementing the scroll history feature, so let me know if you want to do it :)

**Comment by DevManu-de** [comment]
Hello alt-romes,

I made the changes you suggested and I added max input.

Where should I make the pull request to, to master or another branch?

I can implement the scroll feature too. Ill work on it in the next few days.

Thanks for your reply.
DevManu-de

**Comment by DevManu-de** [comment]
Hello alt-romes,

I made the changes you suggested and I added max input.

Where should I make the pull request to, to master or another branch?

I can implement the scroll feature too. Ill work on it in the next few days.

Thanks for your reply.
DevManu-de

**Comment by alt-romes** [comment]
You can make the pull request to master!

If I can test it again without problems I might release a new version, since I fixed another bug.

After that, let me know how the history scrolling is going, we can help as well :)

Thank you as well,
romes
