### ISSUE TITLE
Contibution guideline and code style

### ISSUE THREAD

**Issue by DevManu-de** [alt-romes/programmer-calculator#44]
Hello,

I think we should add a contibution guideline and code style to the project to keep things clear.
The same thing was mentioned in #43 by @Mango0x45.

In the following list I will share some of my ideas.

**Contibution guideline**
1. Before making a pr the entire project should be recompiled with `make clean && make`
2. Changes need to have documentation
3. Prefferably a valgrind check should be performed
4. Commit should have a descriptive name

**Code style**
1. Pointer star is by the variable (i.e. `int *i;`)
2. Functions, loops and if have a space between name and bracket (i.e. `while (i < 10) {`, `int func (int i) {`)
3. The curly bracket start on the same line as the declaration (i.e. `if (a == b) {`)
4. Between variable and operator is a space (i.e. `int i = 1;`, `i += 1;`)

Please let me know what you thin about that. @alt-romes 
This is just a small idea I had and there are some things missing that need to be defined.

DevManu-de

**Comment by kippenjongen** [comment]
I would suggest also specifying whether it uses spaces or tabs, and in the case of spaces how many. At the moment I believe it uses 4 spaces for indentation, but it would be good to specify it too.

**Comment by alt-romes** [comment]
Hey everyone,

@DevManu-de these are good suggestions.

I'll look into creating a simple `CONTRIBUTION.md` file for now, and we can edit it as needed.

If anyone has ideas for the contribution guidelines you can also suggest changes through a pull request.

**Comment by alt-romes** [comment]
I've added a `CONTRIBUTING.md` file, if you think changes could be made please let me know.

Thank you,
~romes
