### ISSUE TITLE
UI isn't adjusted when window is resized

### ISSUE THREAD

**Issue by alt-romes** [alt-romes/programmer-calculator#45]
At the moment, the program doesn't react to the screen size being changed.

It would be best if we could avoid redrawing the ncurses windows boxes and everything else every cycle, and instead react to the window being resized.

This should be implemented if possible in `draw.c`

Thank you,
~romes

**Comment by DevManu-de** [comment]
If someone attempts implementing this, there is a small code part in `main.c`:`get_input()` around the lines `394` that may come in handy.
