### ISSUE TITLE
User options: long options, help and version

### ISSUE THREAD

**Issue by alt-romes** [alt-romes/programmer-calculator#46]
> `-h` normally means "help". Also, prefer `getopt_long`; be nice to your users

Right now we're using `getopt` to handle the user options. It would be better to replace this with `getopt_long` and add the necessary structures to handle long options like `--help`

Also, right now the option `-h` hides the `history`. It would be good to come up with another letter for `history`, and start using `h` for `help`.

Finally, we don't have a `-v`, `--version` option. I thought about hardcoding the version in the program, but if there's a better way let me know.

Thank you,
~romes

**Comment by DevManu-de** [comment]
I ll take a look at this.

**Comment by DevManu-de** [comment]
@alt-romes is this now done?

**Comment by alt-romes** [comment]
Hey @DevManu-de I'm just writing the `help`.

There's a bug. If you write for example `--test` it crashes with `Segmentation fault: 11`

After I commit `help`, and that bug is fixed, we can close this issue

Thank you so much,
~romes

**Comment by DevManu-de** [comment]
Can you please recompile the entire project because the `Segmentation fault: 11` doesnt happen on my machine.

**Comment by alt-romes** [comment]
I thought I had.

Either I didn't, or it had something to do with me editing the story ( I was using a multiline string before deciding to use multiple puts)

Either way, it doesn't seem to happen anymore.

Dankeschön,
~romes
