### ISSUE TITLE
Input window overflows

### ISSUE THREAD

**Issue by kippenjongen** [alt-romes/programmer-calculator#52]
If the terminal isn't wide enough the input can overflow the input window, and the bit that ended up outside isn't removed. 
I think the solution for this would be to check if the input window is big enough for the text and otherwise to add another line to the bottom, but I'd also imagine that it would be handy if #45 is done first, so that the code for checking the window size is already there.
![overflow](https://user-images.githubusercontent.com/23664790/107142637-a86d1580-6930-11eb-841a-5f8197f5d47b.png)
![overflow](https://user-images.githubusercontent.com/23664790/107142711-08fc5280-6931-11eb-8f77-b028b645eec9.png)

**Comment by alt-romes** [comment]
Nice finding!

Either that, or we could limit the number of input read by the max number of columns

Thank you

**Comment by kippenjongen** [comment]
That would also work. I do feel like that would be slightly less pretty, but it would probably be considerably more simple. I'll have a look at doing that now, though it might have to be changed a bit when #45 is done.

**Comment by alt-romes** [comment]
As @kippenjongen mentioned, when the input is long, and the window resized, it'll probably still overflow.
Perhaps that should be dealt in #45 with window resize, so I'm going to close this issue for now.

Thank you for your help!
