### ISSUE TITLE
Decimal numbers and Negative numbers

### ISSUE THREAD

**Issue by Rapta-08** [alt-romes/programmer-calculator#59]
Your program is really fast, but it doesn't calculate decimal numbers and negative numbers. I know it needs a lot of work to be done, but it should be completed as a terminal application with an update like this.

**Comment by alt-romes** [comment]
Have you updated to the latest version?
Version 2.x works with negative numbers and supports parenthesis.

Could you give me an example of the expression you inserted, the expected output, and the actual output?

Thank you!
~romes

**Comment by Rapta-08** [comment]
Well, you updated the code so it is only for arch based distros, and I'm using a debian distro, so I can't update the version..

**Comment by alt-romes** [comment]
@Rapta-08 I think you might have misunderstood! As far as I know the code runs on all unix based systems with ncurses.

To make things easier, there are 2 packages set up - one for homebrew and one in the AUR - these facilitate installation for some systems, but don't prevent anyone else from downloading the code and building it on their own

How did you download/build this program your first time? 
In theory to get the newest version you just have to download the code again, and follow the build instructions again.

(Alternatively, I think you can also install the brew package manager in linux and then install `pcalc` with that installer)
