### ISSUE TITLE
Code documentation and question

### ISSUE THREAD

**Issue by DevManu-de** [alt-romes/programmer-calculator#6]
Hello,

Im working on the history scroll feature and I have a new history system implemented (without scrolling just storing the data) but Im not very happy with it maybe I will start over again. I have problems following the code in `main.c` line 198 to 234. Maybe someone could provide more documentation.

This is the code from line 198 to 234.
```      char * op = strpbrk(in, all_ops);
    if (op != NULL) {
        char opchar[2];
        opchar[0] = *op;
        opchar[1] = '\0';
        *current_op = getopcode(*op);
        char * token = strtok(in, opchar);
        int operationInStack = 0;
        if(token == NULL) {
            if(strcmp(opchar, history.records[history.size-1]))
                add_to_history(opchar);
        } else if (token != NULL && token < op) {
            clear_numberstack(numbers);
            clear_history();
        } else if (token != NULL && op < token) {   
            if(strcmp(opchar, history.records[history.size-1]))
                add_to_history(opchar);
            operationInStack = 1;
        }
        while (token != NULL) {

            long long aux = pushnumber(token, numbers);
            
            if(strstr(token, "0b") != NULL)
                add_number_to_history(aux, 2);
            else if (strstr(token, "0x") != NULL)
                add_number_to_history(aux, 1);
            else
                add_number_to_history(aux, 0);

            if(!operationInStack && strcmp(opchar, history.records[history.size-1])) {
                add_to_history(opchar);
                operationInStack = 1;
            }
        	token = strtok(NULL, opchar);
        }
    }
 ```

In addition to that, can you provide a little more documentation on what exactly `numberstack` holds and how it is used.

Furthermore I want to ask if there is a problem if I split the `main.c` in smaller files this will be handy when the project grows and also for the maintainer and contributors now.

If you want to take a look at the current state (https://github.com/DevManu-de/programmer-calculator/tree/history-scroll). Please dont hesitate to give feedback.

Thanks in advance for the answer.
DevManu-de

**Comment by alt-romes** [comment]
Hey, I've written some documentation, I'll try to write more for the rest another day.

I hope the commented explanations help you understand the `numberstack` and those lines.

Splitting `main.c` could be really helpful, however I'm not sure of the best way to do it. If you have a good idea in mind, you can submit a pull request :)

I saw the current state and I'm not too sure about it, however my friend (@AMPAlves) who is messing with the history scrolling will reply here as well.

Thank you for your collaboration!
romes

**Comment by DevManu-de** [comment]
Hi,

I just have a question, is there a repository where (@AMPAlves) has his version of programmer-calculator with history scrolling.

Thanks
DevManu-de

**Comment by AMPAlves** [comment]
Hello hello , just saw your response , it was more less a few lines of code so I did it all in one commit.

I took your main.c code and formulated it a bit and the history scrolling is fully functional right now. I will push the code to the master branch and give it a new release version. Thanks for the help @DevManu-de !

**Comment by alt-romes** [comment]
@DevManu-de if you want to split `main.c`, it would be a good idea to do it now, let us see what you are thinking about

If there's an issue with splitting it perhaps it would be a better idea to open a new issue.

Thank you again :),
~romes

**Comment by DevManu-de** [comment]
@alt-romes @AMPAlves Im currently looking at the code @AMPAlves pushed and I saw that my compiler is giving me some warnings and the program crashes if I press the arrow keys too often.

If this bug is fixed I will take a look at splitting `main.c`

The compiler warnings can be resolved if `void add_to_searchhistory(char* in);` is added to the top of `main.c`.

For the future I suggest making a pull request first beause there we can easily find those bugs and fix them before a new version is released.

Thanks,
DevManu-de
