### ISSUE TITLE
Support for other hex notations

### ISSUE THREAD

**Issue by alt-romes** [alt-romes/programmer-calculator#60]
I think we should support other hex notations besides `0x`

I think all of the following numbers should also be considered hexadecimal:

`$FF00`, `x3F`, `0x5E`

To implement this please check [line `305` of `src/parser.c`](https://github.com/alt-romes/programmer-calculator/blob/0cdc92779dd8e8fe0f29d8b3e159187817a964af/src/parser.c#L305)

The grammar rule to model should be

* New rule: `number: ( (0-9)+ | ((0x | x | $)(0-9a-f)+) | 0b(0-1)+ )`

instead of 

* Old rule: `number: ( (0-9)+ | 0x(0-9a-f)+ | 0b(0-1)+ )`

Thank you, ~romes

**Comment by DevManu-de** [comment]
I am pretty sure that `$` as a hex notation will lead to confusion with the `nor` gate.

**Comment by alt-romes** [comment]
You're right. I was inspired by an assembly lang, but forget the `$` then :)
