### ISSUE TITLE
Feature request: Colored output

### ISSUE THREAD

**Issue by snaphat** [alt-romes/programmer-calculator#63]
Pretty great cmdline calculator! I think optional colored output would be a great addition to make it easier to read

**Comment by DevManu-de** [comment]
I am implementing this right now.
Does anyone have an idea on which colors for what?

**Comment by DevManu-de** [comment]
I got the code ready (on my fork) but still the question which colors for what.
My fork has one sample on how the colors work.
When this question is solved I will make a pull request.

**Comment by alt-romes** [comment]
Hey @DevManu-de thank you for your work,
I think since you've done it you can go ahead and choose some colours you believe are good
We can tweak it easily later

If it was me I'd try some green or oranges... maybe ;)
