### ISSUE TITLE
Feature request: Swap Endianness

### ISSUE THREAD

**Issue by clarkewd** [alt-romes/programmer-calculator#67]
It would be nice to have a command to switch the byte-order, i.e. switch a number from little-endian (LE) to big-endian (BE)  

eg: If I paste a value encoded as `0xCCBBAA` the command would change it to `0xAABBCC`, and after performing calculations the command could be used to switch it back to little-endian so the value could be copied and pasted elsewhere

Also, this calculator is amazing even without this feature! Thank you!! 😄 👏 🙏

**Comment by alt-romes** [comment]
This has been added in merge request #70 by @drumfreakk !

Thanks for the suggestion

I'm glad it's being useful,
Romes
