### ISSUE TITLE
`cb` consumes more than it should

### ISSUE THREAD

**Issue by selendym** [alt-romes/programmer-calculator#68]
Hello.

Currently, the *change number of bits* command seems to break things, as it will consume every input that has the substring `"cb"` anywhere within it.
This includes all hex numbers that match this, so numbers like `0xcb` are impossible to input as regular numbers, though upper case does work.

The problem is most likely here: https://github.com/alt-romes/programmer-calculator/blob/060c9969170e78e9259e801b3bdfa548fdbbb504/src/main.c#L206

As an easy fix, the substring could be changed to something that doesn't clash with anything else, like `"bits"`.

Best regards.

**Comment by alt-romes** [comment]
@ajcostafct maybe you can tackle this
