### ISSUE TITLE
Typo in readme says ROTATE-LEFT but should say ROTATE-RIGHT

### ISSUE THREAD

**Issue by bc-webmaster** [alt-romes/programmer-calculator#73]
Hi, there's a typo in the readme on what is currently line 158 -- where it says 'ROTATE-LEFT' it should say 'ROTATE-RIGHT'. The explanation later on the line correctly says 'right'.

https://github.com/alt-romes/programmer-calculator/blob/master/README.md?plain=1#L158

**Comment by alt-romes** [comment]
Thanks. Fixed it.
