### ISSUE TITLE
CI infrastructure

### ISSUE THREAD

**Issue by alt-romes** [alt-romes/programmer-calculator#80]
It'd be good to setup a CI infrastructure  that builds and runs the tests automatically.

It'd also be great if new releases (via git tags) could be automatically packaged and distributed!

**Comment by demo-exe** [comment]
Would be nice to add some code prettyfier like uncrustify (and also test whether pr adheres to it)

**Comment by alt-romes** [comment]
Closed by #85.

I'll open a separate issue to track CI packaging
