### ISSUE TITLE
Segfault on invalid arguments

### ISSUE THREAD

**Issue by lukvxx** [alt-romes/programmer-calculator#82]
I noticed, that a segfault occurs when an invalid argument was given.
![Bild 02 02 23 um 13 19](https://user-images.githubusercontent.com/44476930/216323166-ce89357d-4591-4652-b71e-aacafe0b0595.jpg)

**Comment by alt-romes** [comment]
This has been fixed by #76 .

For now, you can clone and compile and install the code with `make && make install`.
Eventually I'll release the fix in a new version
