### ISSUE TITLE
Splitting main.c

### ISSUE THREAD

**Issue by DevManu-de** [alt-romes/programmer-calculator#9]
Hello,

I have a concept on how I think it could look like on my fork (https://github.com/DevManu-de/programmer-calculator).
I made some modifications to the code to get it compiling but currently it doesnt most likely due to all the global variables.
I just want you to take a look at the current state.

DevManu-de

**Comment by alt-romes** [comment]
Hi, it looks seriously impressive!

I think we should do it.

Unfortunately we had to rewrite a commit, but I'll handle the merge errors, no worries.

When you get it compiling let me know, maybe issue a pull request!

Dankeschön,
~romes

**Comment by alt-romes** [comment]
Hi @DevManu-de you did an amazing job splitting the file

It's impressive, and to be completely honest, there are a lot of things I don't understand fully.
I don't have much experience with organising big `c` projects, so thank you for your help.

There's one bug with the makefile, I'll create an issue for it

:)
Thank you,
~romes
